### ISSUE TITLE
Weekly backups

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/maintenance#1]
There is a large number of github repos in the organization. We need to implement an automated mechanism to backup these.

Tentative solution:
Make an API call to the GH org and get the list of repos.
Clone them to a storage server.
Also, we don't have to clone everything every week. We can clone the newly created ones and just pull the lines from last week.

**Comment by NuwanJ** [comment]
Yes. That is a good idea. 

- if already downloaded, run git pull
- otherwise, git clone.

I think this can be done for all public repos without any problem, with a Python Script. For getting backups of the Private repos, we need a personal access token of an Admin, with no expiration date (This thing needs to be carefully considered).

**Comment by NuwanJ** [comment]
@gihanjayatilaka A suggestion is in #18. It can be executed as a corn job.

**Comment by gihanjayatilaka** [comment]
Merged. Thanks!
